import { TranscriptError } from "./errors";
import { fetchBuffer, fetchHead } from "./http";
import { groupWordCues } from "./parse-caption";
import { countWords, flattenCues } from "./time";
import type { Cue, TranscriptResult } from "./types";

const MAX_AUDIO_BYTES = 50 * 1024 * 1024;
const MAX_AUDIO_MS = 2 * 60 * 60 * 1000;
const STT_TIMEOUT_MS = 180_000;

type SttWord = {
  text?: string;
  start?: number;
  end?: number;
  speaker?: number | string;
};

type SttResponse = {
  text?: string;
  language?: string;
  duration?: number;
  words?: SttWord[];
};

export function assertAudioBudget(durationMs?: number, byteLength?: number): void {
  if (durationMs && durationMs > MAX_AUDIO_MS) {
    throw new TranscriptError(
      "too_large",
      "That episode is longer than the 2 hour speech-to-text cap.",
    );
  }
  if (byteLength && byteLength > MAX_AUDIO_BYTES) {
    throw new TranscriptError("too_large", "Audio is over the 50 MB speech-to-text cap.");
  }
}

export async function transcribeEnclosure(opts: {
  enclosureUrl: string;
  title: string;
  author?: string;
  sourceUrl: string;
  canonicalUrl: string;
  durationMs?: number;
}): Promise<TranscriptResult> {
  assertAudioBudget(opts.durationMs);
  const apiKey = process.env.XAI_API_KEY?.trim();
  if (!apiKey) {
    throw new TranscriptError(
      "stt_unavailable",
      "No captions or published transcript, and speech-to-text is unavailable.",
    );
  }

  let byteLength: number | undefined;
  try {
    const head = await fetchHead(opts.enclosureUrl, { timeoutMs: 12_000 });
    const len = Number(head.headers.get("content-length") ?? 0);
    if (Number.isFinite(len) && len > 0) byteLength = len;
  } catch {
    /* HEAD is best-effort */
  }
  assertAudioBudget(opts.durationMs, byteLength);

  const stt = await callXaiStt({ enclosureUrl: opts.enclosureUrl, apiKey, byteLength });
  const cues = cuesFromStt(stt, opts.durationMs);
  if (!cues.length && !stt.text?.trim()) {
    throw new TranscriptError("no_transcript", "Speech-to-text returned an empty transcript.");
  }
  const text = flattenCues(cues.length ? cues : [{ startMs: 0, endMs: opts.durationMs ?? 1000, text: stt.text ?? "" }]);
  return {
    kind: "transcript",
    title: opts.title,
    author: opts.author,
    durationMs: opts.durationMs ?? (stt.duration ? Math.round(stt.duration * 1000) : undefined),
    source: "stt",
    sourceUrl: opts.sourceUrl,
    canonicalUrl: opts.canonicalUrl,
    language: stt.language,
    isAutoGenerated: true,
    cues: cues.length ? cues : [{ startMs: 0, endMs: opts.durationMs ?? 1000, text: stt.text ?? "" }],
    text,
    wordCount: countWords(text),
    fetchedAt: new Date().toISOString(),
  };
}

async function callXaiStt(opts: {
  enclosureUrl: string;
  apiKey: string;
  byteLength?: number;
}): Promise<SttResponse> {
  const form = new FormData();
  form.set("model", "grok-voice-transcribe-2.0");
  form.set("language", "en");
  form.set("format", "true");
  form.set("diarize", "true");

  if (opts.byteLength && opts.byteLength > MAX_AUDIO_BYTES) {
    throw new TranscriptError("too_large", "Audio is over the 50 MB speech-to-text cap.");
  }
  form.set("url", opts.enclosureUrl);

  const res = await fetch("https://api.x.ai/v1/stt", {
    method: "POST",
    headers: { Authorization: `Bearer ${opts.apiKey}` },
    body: form,
    signal: AbortSignal.timeout(STT_TIMEOUT_MS),
  }).catch((err: unknown) => {
    if (err instanceof Error && (err.name === "TimeoutError" || err.name === "AbortError")) {
      throw new TranscriptError("timeout", "Speech-to-text timed out.");
    }
    throw new TranscriptError("network", "Could not reach speech-to-text.");
  });

  if (res.status === 413) {
    return callXaiSttWithFile(opts);
  }
  if (!res.ok) {
    if (res.status === 401 || res.status === 403) {
      throw new TranscriptError("stt_unavailable", "Speech-to-text refused the request.");
    }
    const fallback = await callXaiSttWithFile(opts).catch(() => null);
    if (fallback) return fallback;
    throw new TranscriptError("no_transcript", `Speech-to-text failed (${res.status}).`);
  }
  return (await res.json()) as SttResponse;
}

async function callXaiSttWithFile(opts: { enclosureUrl: string; apiKey: string }): Promise<SttResponse> {
  const buf = await fetchBuffer(opts.enclosureUrl, {
    timeoutMs: 90_000,
    maxBytes: MAX_AUDIO_BYTES,
  });
  const form = new FormData();
  form.set("model", "grok-voice-transcribe-2.0");
  form.set("language", "en");
  form.set("format", "true");
  form.set("diarize", "true");
  form.set("file", new File([Buffer.from(buf)], "episode.mp3", { type: "audio/mpeg" }));
  const res = await fetch("https://api.x.ai/v1/stt", {
    method: "POST",
    headers: { Authorization: `Bearer ${opts.apiKey}` },
    body: form,
    signal: AbortSignal.timeout(STT_TIMEOUT_MS),
  });
  if (!res.ok) {
    throw new TranscriptError("no_transcript", `Speech-to-text failed (${res.status}).`);
  }
  return (await res.json()) as SttResponse;
}

function cuesFromStt(stt: SttResponse, durationMs?: number): Cue[] {
  const words: Cue[] = [];
  for (const w of stt.words ?? []) {
    const text = (w.text ?? "").trim();
    if (!text) continue;
    const startMs = Math.round((w.start ?? 0) * 1000);
    const endMs = Math.round((w.end ?? (w.start ?? 0) + 0.4) * 1000);
    const speaker = w.speaker == null ? undefined : `Speaker ${w.speaker}`;
    words.push({ startMs, endMs, text, speaker });
  }
  if (words.length) return groupWordCues(words);
  const text = (stt.text ?? "").trim();
  if (!text) return [];
  const sentences = text.split(/(?<=[.!?])\s+/).filter(Boolean);
  const total = durationMs && durationMs > 0 ? durationMs : sentences.length * 3000;
  const slice = total / Math.max(sentences.length, 1);
  return sentences.map((sentence, i) => ({
    startMs: Math.round(i * slice),
    endMs: Math.round((i + 1) * slice),
    text: sentence,
  }));
}
