export type Cue = {
  startMs: number;
  endMs: number;
  text: string;
  speaker?: string;
};

export type TranscriptSource =
  | "youtube"
  | "podcast"
  | "rss"
  | "stt"
  | "file";

export type CollectionSource = "youtube" | "apple" | "spotify" | "rss";

export type TranscriptResult = {
  kind: "transcript";
  title: string;
  author?: string;
  durationMs?: number;
  source: TranscriptSource;
  sourceUrl: string;
  canonicalUrl: string;
  language?: string;
  isAutoGenerated?: boolean;
  cues: Cue[];
  text: string;
  wordCount: number;
  fetchedAt: string;
};

export type CollectionItem = {
  title: string;
  url: string;
  feedUrl?: string;
  guid?: string;
  durationMs?: number;
  publishedAt?: string;
  author?: string;
  thumbnailUrl?: string;
};

export type CollectionResult = {
  kind: "collection";
  title: string;
  author?: string;
  source: CollectionSource;
  sourceUrl: string;
  items: CollectionItem[];
};

export type FetchErrorCode =
  | "invalid_url"
  | "no_transcript"
  | "blocked"
  | "no_audio"
  | "timeout"
  | "not_found"
  | "unsupported"
  | "rate_limited"
  | "stt_unavailable"
  | "too_large"
  | "network"
  | "unknown";

export type ErrorResult = {
  kind: "error";
  code: FetchErrorCode;
  message: string;
  hint?: string;
};

export type FetchResponse = TranscriptResult | CollectionResult | ErrorResult;

export type BatchResult = {
  kind: "batch";
  results: FetchResponse[];
};

export type AgentResponse = FetchResponse | BatchResult;

export type TranscriptInput = {
  url: string;
  feedUrl?: string;
  guid?: string;
};

export type ParsedUrlKind =
  | "youtube-video"
  | "youtube-playlist"
  | "apple-episode"
  | "apple-show"
  | "spotify-episode"
  | "spotify-show"
  | "rss"
  | "unknown";

export type ParsedSourceUrl = {
  kind: ParsedUrlKind;
  originalUrl: string;
  canonicalUrl: string;
  videoId?: string;
  playlistId?: string;
  appleShowId?: string;
  appleEpisodeId?: string;
  spotifyId?: string;
};

export type JobStatus =
  | "queued"
  | "running"
  | "done"
  | "error"
  | "collection"
  | "paused";

export type Job = {
  id: string;
  url: string;
  feedUrl?: string;
  guid?: string;
  label: string;
  status: JobStatus;
  error?: string;
  hint?: string;
  errorCode?: FetchErrorCode;
  transcript?: TranscriptResult;
  collection?: CollectionResult;
};

export type HistoryItem = {
  title: string;
  author?: string;
  wordCount?: number;
  url: string;
  canonicalUrl: string;
  savedAt: string;
};

export type ExportFormat = "txt" | "md" | "srt" | "vtt" | "json";
