import { TranscriptError } from "./errors";
import { BROWSER_UA, extractJsonObject, fetchJson, fetchResponse, fetchText, stripHtml } from "./http";
import { isGoodEpisodeMatch } from "./match";
import { parseCaptionBytes } from "./parse-caption";
import { countWords, flattenCues, parseClockToMs } from "./time";
import type { CollectionItem, CollectionResult, Cue, TranscriptResult } from "./types";
import type { ParsedSourceUrl } from "./types";

const WEB_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";
const ANDROID_KEY = "AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w";
const COLLECTION_CAP = 40;
const YT_COOKIES = "CONSENT=YES+; SOCS=CAI";

type PlayerResponse = {
  videoDetails?: {
    videoId?: string;
    title?: string;
    author?: string;
    lengthSeconds?: string;
    shortDescription?: string;
  };
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: CaptionTrack[];
    };
  };
  playabilityStatus?: {
    status?: string;
    reason?: string;
  };
  microformat?: {
    playerMicroformatRenderer?: {
      ownerChannelName?: string;
      lengthSeconds?: string;
    };
  };
};

type CaptionTrack = {
  baseUrl?: string;
  languageCode?: string;
  name?: { simpleText?: string } | string;
  kind?: string;
  vssId?: string;
};

type InnertubeClient = {
  name: string;
  version: string;
  key?: string;
  extra?: Record<string, unknown>;
};

const CLIENTS: InnertubeClient[] = [
  { name: "ANDROID", version: "19.29.37", key: ANDROID_KEY, extra: { androidSdkVersion: 30 } },
  { name: "WEB_EMBEDDED_PLAYER", version: "1.20241201.00.00" },
  { name: "IOS", version: "19.29.1", extra: { deviceMake: "Apple", deviceModel: "iPhone16,2" } },
  { name: "TVHTML5_SIMPLY_EMBEDDED_PLAYER", version: "2.0" },
  { name: "WEB", version: "2.20241201.01.00", key: WEB_KEY },
];

export async function resolveYoutube(parsed: ParsedSourceUrl): Promise<TranscriptResult | CollectionResult> {
  if (parsed.kind === "youtube-playlist" || (!parsed.videoId && parsed.playlistId)) {
    return fetchPlaylist(parsed.playlistId!, parsed.canonicalUrl);
  }
  if (!parsed.videoId) {
    throw new TranscriptError("invalid_url", "That YouTube link is missing a video id.");
  }
  return fetchVideoTranscript(parsed.videoId, parsed.canonicalUrl);
}

export async function fetchVideoTranscript(videoId: string, sourceUrl: string): Promise<TranscriptResult> {
  const player = await loadPlayer(videoId);
  const status = player.playabilityStatus?.status;
  if (status && status !== "OK") {
    const reason = player.playabilityStatus?.reason ?? status;
    if (status === "LOGIN_REQUIRED" || status === "UNPLAYABLE" || /sign in|unavailable|private/i.test(reason)) {
      throw new TranscriptError("blocked", `YouTube blocked playback (${reason}).`);
    }
    if (status === "ERROR") {
      throw new TranscriptError("not_found", reason || "YouTube could not find that video.");
    }
  }
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  if (!tracks.length) {
    throw new TranscriptError(
      "no_transcript",
      "This video has no caption track.",
      "YouTube only returns a transcript when captions exist. Auto-ASR is used when that is all there is.",
    );
  }
  const track = pickCaptionTrack(tracks);
  if (!track?.baseUrl) {
    throw new TranscriptError("no_transcript", "Caption tracks were listed but none could be downloaded.");
  }
  const { cues, isAutoGenerated, language } = await downloadTrack(track);
  if (!cues.length) {
    throw new TranscriptError("no_transcript", "The caption track was empty.");
  }
  const details = player.videoDetails;
  const durationSec = Number(details?.lengthSeconds ?? player.microformat?.playerMicroformatRenderer?.lengthSeconds ?? 0);
  const text = flattenCues(cues);
  return {
    kind: "transcript",
    title: details?.title || `YouTube ${videoId}`,
    author: details?.author || player.microformat?.playerMicroformatRenderer?.ownerChannelName,
    durationMs: Number.isFinite(durationSec) && durationSec > 0 ? durationSec * 1000 : undefined,
    source: "youtube",
    sourceUrl,
    canonicalUrl: `https://www.youtube.com/watch?v=${videoId}`,
    language,
    isAutoGenerated,
    cues,
    text,
    wordCount: countWords(text),
    fetchedAt: new Date().toISOString(),
  };
}

export async function searchYoutubeForEpisode(
  title: string,
  author?: string,
  durationMs?: number,
): Promise<TranscriptResult | null> {
  const query = [title, author, "podcast"].filter(Boolean).join(" ");
  const hits = await searchYoutube(query);
  for (const hit of hits.slice(0, 8)) {
    if (!isGoodEpisodeMatch(title, hit.title, durationMs, hit.durationMs)) continue;
    try {
      const transcript = await fetchVideoTranscript(hit.videoId, `https://www.youtube.com/watch?v=${hit.videoId}`);
      if (isGoodEpisodeMatch(title, transcript.title, durationMs, transcript.durationMs)) {
        return transcript;
      }
    } catch {
      continue;
    }
  }
  return null;
}

async function loadPlayer(videoId: string): Promise<PlayerResponse> {
  const fromWatch = await playerFromWatchPage(videoId);
  if (fromWatch && hasUsablePlayer(fromWatch)) return fromWatch;

  let lastErr: unknown;
  for (const client of CLIENTS) {
    try {
      const player = await playerFromInnertube(videoId, client);
      if (hasUsablePlayer(player) || player.playabilityStatus) return player;
    } catch (err) {
      lastErr = err;
    }
  }
  if (fromWatch) return fromWatch;
  if (lastErr instanceof TranscriptError) throw lastErr;
  throw new TranscriptError("blocked", "YouTube did not return a player response.");
}

function hasUsablePlayer(player: PlayerResponse): boolean {
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  return Boolean(tracks?.length) || player.playabilityStatus?.status === "OK";
}

async function playerFromWatchPage(videoId: string): Promise<PlayerResponse | null> {
  try {
    const html = await fetchText(`https://www.youtube.com/watch?v=${videoId}&hl=en&bpctr=9999999999&has_verified=1`, {
      timeoutMs: 18_000,
      headers: { Cookie: YT_COOKIES, "Accept-Language": "en-US,en;q=0.9" },
      userAgent: BROWSER_UA,
    });
    const json =
      extractJsonObject(html, "ytInitialPlayerResponse") ??
      extractJsonObject(html, "var ytInitialPlayerResponse");
    return (json as PlayerResponse) ?? null;
  } catch {
    return null;
  }
}

async function playerFromInnertube(videoId: string, client: InnertubeClient): Promise<PlayerResponse> {
  const key = client.key ?? WEB_KEY;
  const url = `https://www.youtube.com/youtubei/v1/player?prettyPrint=false&key=${key}`;
  const body = {
    context: {
      client: {
        clientName: client.name,
        clientVersion: client.version,
        hl: "en",
        gl: "US",
        ...client.extra,
      },
      thirdParty: client.name.includes("EMBEDDED") ? { embedUrl: "https://www.youtube.com/" } : undefined,
    },
    videoId,
    contentCheckOk: true,
    racyCheckOk: true,
  };
  return fetchJson<PlayerResponse>(url, {
    method: "POST",
    body: JSON.stringify(body),
    timeoutMs: 18_000,
    headers: {
      "Content-Type": "application/json",
      Cookie: YT_COOKIES,
      Origin: "https://www.youtube.com",
      Referer: `https://www.youtube.com/watch?v=${videoId}`,
      "X-YouTube-Client-Name": client.name === "ANDROID" ? "3" : "1",
      "X-YouTube-Client-Version": client.version,
    },
    userAgent: client.name === "ANDROID" ? "com.google.android.youtube/19.29.37 (Linux; U; Android 14)" : BROWSER_UA,
  });
}

function pickCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | undefined {
  const scored = tracks
    .filter((t) => t.baseUrl)
    .map((t) => {
      const lang = (t.languageCode ?? "").toLowerCase();
      const auto = t.kind === "asr" || (t.vssId ?? "").startsWith("a.");
      let score = 0;
      if (lang === "en" || lang.startsWith("en-")) score += 50;
      else if (lang === "en-orig" || lang.includes("en")) score += 40;
      if (!auto) score += 30;
      if (lang === "en" && !auto) score += 20;
      return { t, score };
    })
    .sort((a, b) => b.score - a.score);
  return scored[0]?.t ?? tracks[0];
}

async function downloadTrack(track: CaptionTrack): Promise<{
  cues: Cue[];
  isAutoGenerated: boolean;
  language?: string;
}> {
  const base = decodeAmp(track.baseUrl ?? "");
  if (!base) throw new TranscriptError("no_transcript", "Caption URL was empty.");
  const jsonUrl = withFmt(base, "json3");
  const attempts = [jsonUrl, withFmt(base, "vtt"), base];
  let lastErr: unknown;
  for (const url of attempts) {
    try {
      const res = await fetchResponse(url, {
        timeoutMs: 25_000,
        headers: { Cookie: YT_COOKIES },
        userAgent: BROWSER_UA,
      });
      if (!res.ok) continue;
      const buf = new Uint8Array(await res.arrayBuffer());
      const mime =
        url.includes("fmt=json3") ? "application/json3" : url.includes("fmt=vtt") ? "text/vtt" : res.headers.get("content-type") ?? "";
      const cues = parseCaptionBytes(buf, mime);
      if (cues.length) {
        return {
          cues,
          isAutoGenerated: track.kind === "asr" || (track.vssId ?? "").startsWith("a."),
          language: track.languageCode,
        };
      }
    } catch (err) {
      lastErr = err;
    }
  }
  if (lastErr instanceof TranscriptError) throw lastErr;
  throw new TranscriptError("no_transcript", "Could not parse the caption track.");
}

function withFmt(url: string, fmt: string): string {
  try {
    const u = new URL(url);
    u.searchParams.set("fmt", fmt);
    return u.toString();
  } catch {
    const joiner = url.includes("?") ? "&" : "?";
    return `${url}${joiner}fmt=${fmt}`;
  }
}

function decodeAmp(url: string): string {
  return url.replace(/&/g, "&");
}

export async function fetchPlaylist(playlistId: string, sourceUrl: string): Promise<CollectionResult> {
  const items = await playlistItems(playlistId);
  if (!items.length) {
    throw new TranscriptError("not_found", "That playlist is empty or unavailable.");
  }
  return {
    kind: "collection",
    title: items[0]?.author ? `${items[0].author} playlist` : "YouTube playlist",
    author: items[0]?.author,
    source: "youtube",
    sourceUrl,
    items: items.slice(0, COLLECTION_CAP),
  };
}

async function playlistItems(playlistId: string): Promise<CollectionItem[]> {
  try {
    const html = await fetchText(`https://www.youtube.com/playlist?list=${playlistId}`, {
      timeoutMs: 18_000,
      headers: { Cookie: YT_COOKIES },
    });
    const data = extractJsonObject(html, "ytInitialData") as Record<string, unknown> | null;
    const found = walkPlaylist(data);
    if (found.length) return found;
  } catch {
    /* fall through to innertube */
  }
  try {
    const json = await fetchJson<Record<string, unknown>>(
      `https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&key=${WEB_KEY}`,
      {
        method: "POST",
        body: JSON.stringify({
          context: { client: { clientName: "WEB", clientVersion: "2.20241201.01.00", hl: "en" } },
          browseId: `VL${playlistId}`,
        }),
        headers: { "Content-Type": "application/json", Cookie: YT_COOKIES, Origin: "https://www.youtube.com" },
        timeoutMs: 18_000,
      },
    );
    return walkPlaylist(json);
  } catch {
    return [];
  }
}

function walkPlaylist(node: unknown, acc: CollectionItem[] = []): CollectionItem[] {
  if (!node || acc.length >= COLLECTION_CAP) return acc;
  if (Array.isArray(node)) {
    for (const child of node) walkPlaylist(child, acc);
    return acc;
  }
  if (typeof node !== "object") return acc;
  const rec = node as Record<string, unknown>;
  const renderer = rec.playlistVideoRenderer as Record<string, unknown> | undefined;
  if (renderer?.videoId) {
    const videoId = String(renderer.videoId);
    const title = textRuns(renderer.title) || `Video ${videoId}`;
    const length = textRuns(renderer.lengthText);
    acc.push({
      title,
      url: `https://www.youtube.com/watch?v=${videoId}`,
      durationMs: parseClockToMs(length),
      thumbnailUrl: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      author: textRuns(renderer.shortBylineText),
    });
    return acc;
  }
  for (const value of Object.values(rec)) walkPlaylist(value, acc);
  return acc;
}

function textRuns(value: unknown): string {
  if (!value) return "";
  if (typeof value === "string") return stripHtml(value);
  if (typeof value === "object") {
    const rec = value as Record<string, unknown>;
    if (typeof rec.simpleText === "string") return rec.simpleText;
    if (Array.isArray(rec.runs)) {
      return rec.runs.map((r) => (r && typeof r === "object" && "text" in r ? String((r as { text: string }).text) : "")).join("");
    }
  }
  return "";
}

type SearchHit = { videoId: string; title: string; durationMs?: number; author?: string };

async function searchYoutube(query: string): Promise<SearchHit[]> {
  try {
    const json = await fetchJson<Record<string, unknown>>(
      `https://www.youtube.com/youtubei/v1/search?prettyPrint=false&key=${WEB_KEY}`,
      {
        method: "POST",
        body: JSON.stringify({
          context: { client: { clientName: "WEB", clientVersion: "2.20241201.01.00", hl: "en" } },
          query,
        }),
        headers: { "Content-Type": "application/json", Cookie: YT_COOKIES, Origin: "https://www.youtube.com" },
        timeoutMs: 18_000,
      },
    );
    const hits = walkSearch(json);
    if (hits.length) return hits;
  } catch {
    /* scrape */
  }
  try {
    const html = await fetchText(`https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`, {
      timeoutMs: 18_000,
      headers: { Cookie: YT_COOKIES },
    });
    const data = extractJsonObject(html, "ytInitialData");
    return walkSearch(data);
  } catch {
    return [];
  }
}

function walkSearch(node: unknown, acc: SearchHit[] = []): SearchHit[] {
  if (!node || acc.length >= 16) return acc;
  if (Array.isArray(node)) {
    for (const child of node) walkSearch(child, acc);
    return acc;
  }
  if (typeof node !== "object") return acc;
  const rec = node as Record<string, unknown>;
  const renderer = rec.videoRenderer as Record<string, unknown> | undefined;
  if (renderer?.videoId) {
    acc.push({
      videoId: String(renderer.videoId),
      title: textRuns(renderer.title),
      durationMs: parseClockToMs(textRuns(renderer.lengthText)),
      author: textRuns(renderer.ownerText) || textRuns(renderer.shortBylineText),
    });
    return acc;
  }
  for (const value of Object.values(rec)) walkSearch(value, acc);
  return acc;
}
